version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5435:5432"
    volumes:
      - postgres_auth:/var/lib/postgresql/data

volumes:
  postgres_auth: